export const ARTICLE_VERSION_CACHE_PREFIX = 'article_version';
export const ARTICLE_VERSION_CACHE_TTL = 3600; // 1 hour
export const ARTICLE_VERSION_MAX_PER_ARTICLE = 50;
export const ARTICLE_VERSION_DIFF_CONTEXT_LINES = 3;
export const ARTICLE_VERSION_DEFAULT_PAGE_LIMIT = 20;
export const ARTICLE_VERSION_AUTO_SAVE_INTERVAL_SECONDS = 30;
