export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: 'AUTH_001',
  TOKEN_EXPIRED: 'AUTH_002',
  INVALID_TOKEN: 'AUTH_003',
  FORBIDDEN: 'AUTH_004',

  // User
  USER_NOT_FOUND: 'USER_001',
  USER_ALREADY_EXISTS: 'USER_002',
  USER_BLOCKED: 'USER_003',
  USER_DELETED: 'USER_004',
  INVALID_CREDENTIALS: 'USER_005',

  // Resource
  NOT_FOUND: 'RES_001',
  ALREADY_EXISTS: 'RES_002',
  VALIDATION_ERROR: 'RES_003',

  // Server
  INTERNAL_ERROR: 'SRV_001',
  DATABASE_ERROR: 'SRV_002',
  RATE_LIMIT_EXCEEDED: 'SRV_003',
} as const;

export type TErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
